#!/bin/bash
CONTENT_SERVER=10.211.55.18
META_SERVER=10.211.55.18
NAME_SERVER=10.211.55.19


RIAK_VMARGS=/etc/riak/vm.args
RIAK_VMARGS_BAK=/etc/riak/vm.args_bak
RIAK_APPCONFIG=/etc/riak/app.config
RIAK_APPCONFIG_BAK=/etc/riak/app.config_bak
RIAK_HTTP_PORT=8098


checkfile=( curl \
        git \
        sss \
        sssd \
        )
